apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: june19-norhoai
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/june19-norhoai:8f7d82013f0f7800c35920bae94277e3714131fd@sha256:12ab12bce55379ee075150bd8b7aed0644fc5a0edc4a8b9a5f4796da9b14fabc # use pre-built to bootstrap
          name: app-inference
