apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: june19-norhoai
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: june19-norhoai
  name: june19-norhoai
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: june19-norhoai
    weight: 100
  wildcardPolicy: None
